### ISSUE TITLE
Need /etc/shadowsocks-libev directory exists before exec generate_config fn

### ISSUE THREAD

**Issue by dafanasiev** [selivan/selivan.github.io-socks#1]
You need to create `/etc/shadowsocks-libev` directory before write file `/etc/shadowsocks-libev/config.json`  (bug in file https://selivan.github.io/shadowsocks.txt)

**Comment by selivan** [comment]
`apt install shadowsocks-libev` should create this directory. How did you get this error?

**Comment by dafanasiev** [comment]
Hmmm, you can see same `mkdir -p ..` hack inside postinst **configure** target inside original  [shadowsocks-libev.postinst](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.postinst#L22)...

I just try to install using you script on empty ubuntu:
```
...skipped
The following NEW packages will be installed:
  apg libev4 libmbedcrypto0 libsodium18 libudns0 shadowsocks-libev
0 upgraded, 6 newly installed, 0 to remove and 50 not upgraded.
Need to get 453 kB of archives.
After this operation, 1,769 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
bash: line 17: /etc/shadowsocks-libev/config.json: No such file or directory
Failed to execute operation: No such file or directory
Failed to restart shadowsocks-libev.service: Unit shadowsocks-libev.service not found.
...
```

PS: Кстати dig тоже не факт что стоит,  `apt install dnsutils` напрашивается...

**Comment by selivan** [comment]
The package is assembled wrong, good practice is to include /etc/shadowsocks-libev/config.json in the package, so that dpkg recognizes it as package configuration file.

Fixed it, thank you for the report.
